name = "RankRevealing"
uuid = "56660b65-79ce-4ef5-9ae7-a20c7f920b12"
authors = ["Iago Leal <iago@iagoleal.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
