name = "RankRevealing"
uuid = "56660b65-79ce-4ef5-9ae7-a20c7f920b12"
authors = ["Iago Leal <iago.lealf@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
